package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.MenuItem;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;


public class BookinfoController {
	@FXML
	private TextField textfield;
	@FXML
	private Button btn_search;
	@FXML
	private MenuItem borrow10days;
	@FXML
	private MenuItem borrow20days;
	@FXML
	private MenuItem borrow30days;
	@FXML
	private Button btn_reserve;
	@FXML
	private Button btn_homepage;

	// Event Listener on Button[#btn_search].onAction
	@FXML
	public void clicktoSearch(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#borrow10days].onAction
	@FXML
	public void clicktoBorrow10days(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#borrow20days].onAction
	@FXML
	public void clicktoBorrow20days(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#borrow30days].onAction
	@FXML
	public void clicktoBorrow30days(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn_reserve].onAction
	@FXML
	public void clicktoReserve(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn_homepage].onAction
	@FXML
	public void clicktoHomepage(ActionEvent event) {
		// TODO Autogenerated
		try {
	    	 Parent homePage = FXMLLoader.load(getClass().getClassLoader().getResource("view/homepage.fxml"));

	         // Create a new scene with the next page content
	         Scene scene = new Scene(homePage);

	         // Get the current stage (primaryStage) from the button's scene
	         Stage primaryStage = (Stage) btn_homepage.getScene().getWindow();

	         // Set the new scene on the stage (Switch to the next page)
	         primaryStage.setScene(scene);
	         primaryStage.setResizable(false);
	         primaryStage.setTitle("homePage"); // Set the title of the next page
	         primaryStage.show();
				
	    	}
	    	catch(IOException e) {
	    		e.printStackTrace();
	    	}
	}
}
