package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;
import javafx.stage.Stage;

public class ChangePassController {
	@FXML
	private PasswordField former_password;
	@FXML
	private PasswordField new_password;
	@FXML
	private PasswordField confirm_new_password;
	@FXML
	private Button btn_homepage;
	@FXML
	private Button btn_change;

	// Event Listener on Button[#btn_homepage].onAction
	@FXML
	public void clicktoHomepage(ActionEvent event) {
		// TODO Autogenerated
		try {
	    	 Parent homePage = FXMLLoader.load(getClass().getClassLoader().getResource("view/homepage.fxml"));

	         // Create a new scene with the next page content
	         Scene scene = new Scene(homePage);

	         // Get the current stage (primaryStage) from the button's scene
	         Stage primaryStage = (Stage) btn_homepage.getScene().getWindow();

	         // Set the new scene on the stage (Switch to the next page)
	         primaryStage.setScene(scene);
	         primaryStage.setResizable(false);
	         primaryStage.setTitle("homePage"); // Set the title of the next page
	         primaryStage.show();
				
	    	}
	    	catch(IOException e) {
	    		e.printStackTrace();
	    	}
	}
	// Event Listener on Button[#btn_change].onAction
	@FXML
	public void clicktoChange(ActionEvent event) {
		// TODO Autogenerated
	  if( (!former_password.getText().equals(""))  && (!former_password.getText().equals(""))  && (!former_password.getText().equals(""))) {	
		try {
			String former_pass = former_password.getText();
			String new_pass = new_password.getText();
			String confirm_pass = confirm_new_password.getText();
			String id = session.Session.getUserID();
			String getPass = "select password from user where ID=?";
			PreparedStatement stamt = connectMysql.Connnector.executePreparedStatement(getPass);
			stamt.setString(1, id);
			ResultSet res = stamt.executeQuery();
			res.next();
			if(res.getString("password").equals(former_pass)) {//check whether the input former password is correct
				if(former_pass.equals(new_pass)) {
					Alert alert = new Alert(AlertType.WARNING);
					alert.setContentText("Your new password is same as your former password!");
					alert.showAndWait();
				}
				else {
					if(!new_pass.equals(confirm_pass)) {
						Alert alert = new Alert(AlertType.WARNING);
						alert.setContentText("Your new passwords are different, please confirm it again!");
						alert.showAndWait();
					}
					else {
					
						String sql = "update user set password=? where ID=?";
						PreparedStatement stmt = connectMysql.Connnector.executePreparedStatement(sql);
						stmt.setString(1, new_pass);
						stmt.setString(2, id);
						stmt.executeUpdate();
						String check = "select ID,password from user where ID=? and password=?";
						stmt = connectMysql.Connnector.executePreparedStatement(check);
						stmt.setString(1, id);
						stmt.setString(2, new_pass);
						ResultSet rs = stmt.executeQuery();
						while(rs.next()) {
							Alert alert = new Alert(AlertType.INFORMATION);
							alert.setContentText("Your  password has been changed successfully!");
							alert.showAndWait();
						}
					}
				}
			}
			else {//input former password is not correct
				Alert alert = new Alert(AlertType.WARNING);
				alert.setContentText("Your former password is not correct!");
				alert.showAndWait();
			}
		}
		catch(Exception e) {
			e.printStackTrace();
		}
	  }// user filled all 3 text fields
	  else {// user has not filled all 3 text fields
		  Alert alert = new Alert(AlertType.WARNING);
		  alert.setContentText("please fill in all 3 textfileds!");
		  alert.showAndWait();
	  }
	}
}
