package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javafx.scene.control.Alert;
import javafx.event.ActionEvent;

public class ChangeProfileController {
	@FXML
	private TextField name_textfield;
	@FXML
	private TextField email_textfield;
	@FXML
	private Button btn_homepage;

    @FXML
    public void clicktoConfirm(ActionEvent event) {
    	try 
    	{
    	String new_name = name_textfield.getText();
    	String new_email = email_textfield.getText();
    	String user_id = session.Session.getUserID();
    	String old_name = null;
    	String old_email = null;
    	
    	String checkProfile = "select name,email from user where ID=?";
    	PreparedStatement stmt = connectMysql.Connnector.executePreparedStatement(checkProfile);
    	stmt.setString(1, user_id);
    	ResultSet rs = stmt.executeQuery();
    	while(rs.next()) {
    		old_name = rs.getString("name");
    		old_email = rs.getString("email");
    	}
    	if(( !new_name.equals("") ) && ( !new_name.equals(old_name) )) {
    		String updateUser = "update user set name=? where ID=?";
    		stmt = connectMysql.Connnector.executePreparedStatement(updateUser);
    		stmt.setString(1, new_name);
    		stmt.setString(2, user_id);
    		stmt.executeUpdate();
    		Alert alert = new Alert(AlertType.INFORMATION);
    		alert.setContentText("Your have changed your name successfully!");
    		alert.showAndWait();
    	}
    	else {
    		Alert alert = new Alert(AlertType.WARNING);
    		alert.setContentText("Your input name is void or it is the same as your name in system, please check again!");
    		alert.showAndWait();
    	}
    	if(( !new_email.equals("") ) && ( !new_email.equals(old_email) )) {
    		String updateUser = "update user set email=? where ID=?";
    		stmt = connectMysql.Connnector.executePreparedStatement(updateUser);
    		stmt.setString(1, new_email);
    		stmt.setString(2, user_id);
    		stmt.executeUpdate();
    		Alert alert = new Alert(AlertType.INFORMATION);
    		alert.setContentText("Your have changed your email successfully!");
    		alert.showAndWait();
    	}
    	else {
    		Alert alert = new Alert(AlertType.WARNING);
    		alert.setContentText("Your input email is void or it is the same as your name in system, please check again!");
    		alert.showAndWait();
    	}
    	}
    	catch(SQLException e) {
    		e.printStackTrace();
    	}
    }
	
	// Event Listener on Button[#btn_homepage].onAction
	@FXML
	public void clicktoHomepage(ActionEvent event) {
		// TODO Autogenerated
		try {	
	    	 Parent homePage = FXMLLoader.load(getClass().getClassLoader().getResource("view/homepage.fxml"));

	         // Create a new scene with the next page content
	         Scene scene = new Scene(homePage);

	         // Get the current stage (primaryStage) from the button's scene
	         Stage primaryStage = (Stage) btn_homepage.getScene().getWindow();

	         // Set the new scene on the stage (Switch to the next page)
	         primaryStage.setScene(scene);
	         primaryStage.setResizable(false);
	         primaryStage.setTitle("homePage"); // Set the title of the next page
	         primaryStage.show();
				
	    	}
	    	catch(IOException e) {
	    		e.printStackTrace();
	    	}
	}
}
