package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.control.Alert.AlertType;
import javafx.stage.Stage;
import javafx.event.ActionEvent;
import java.sql.*;
import java.io.IOException;

public class SignupController {
	@FXML
	private Button btn_register;

    @FXML
    private TextField ID_textfield;

    @FXML
    private TextField email_textfield;

    @FXML
    private TextField name_textfield;
    
    @FXML
    private PasswordField password_field;
    
    @FXML
    private PasswordField confirm_password;
    
    
	// Event Listener on Button[#btn_register].onAction
	@FXML
	public void clickRegister(ActionEvent event) {
		// TODO Autogenerated
		try {
			String user_id = ID_textfield.getText();
			String email = email_textfield.getText();
			String name = name_textfield.getText();
			String password = password_field.getText();
			String confirm = confirm_password.getText();
			if(!password.equals(confirm)) {
				Alert alert = new Alert(AlertType.WARNING);
				alert.setContentText("Please confirm your password again.");
				alert.showAndWait();
			}
			else{
			String sql ="select ID from user where ID = ?";
			PreparedStatement stmt = connectMysql.Connnector.executePreparedStatement(sql);
			stmt.setString(1,user_id);
			ResultSet rs = stmt.executeQuery();
			if (rs.next()) {
				// User ID was registered
				Alert alert = new Alert(AlertType.WARNING);
	            alert.setTitle("existed ID");
	            alert.setHeaderText(null);
	            alert.setContentText("This user ID has been registered. Please try again.");
	            
	            // Show the Alert dialog
	            alert.showAndWait();
			}
			
			else {
				
				String insert_sql = "INSERT INTO user(`ID`, `name`, `email`, `password`) VALUES (?, ?, ?, ?)";
				PreparedStatement statemt = connectMysql.Connnector.executePreparedStatement(insert_sql);
				statemt.setString(1, user_id);
				statemt.setString(2, name);
				statemt.setString(3, email);
				statemt.setString(4,password);
				statemt.executeUpdate();
				Alert alert = new Alert(AlertType.INFORMATION);
				alert.setContentText("You have registered successfully. Close this window to enter user homepage");
				alert.showAndWait();
				
				new session.Session().setUserID(user_id);
				// Load the next page FXML file
	            Parent homePage = FXMLLoader.load(getClass().getClassLoader().getResource("view/homepage.fxml"));

	            // Create a new scene with the next page content
	            Scene scene = new Scene(homePage);

	            // Get the current stage (primaryStage) from the button's scene
	            Stage primaryStage = (Stage) btn_register.getScene().getWindow();

	            // Set the new scene on the stage (Switch to the next page)
	            primaryStage.setScene(scene);
	            primaryStage.setResizable(false);
	            primaryStage.setTitle("homePage"); // Set the title of the next page
	            primaryStage.show();
				}
			}
		}
		catch(SQLException e) {
			e.printStackTrace();
		}
		catch(IOException e) {
			e.printStackTrace();
		}
	}
}
