package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class signup_pageController {
	@FXML
	private Button btn_register;

	// Event Listener on Button[#btn_register].onAction
	@FXML
	public void clickRegister(ActionEvent event) {
		// TODO Autogenerated
	}
}
